# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-14 23:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20170810_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number_of_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
