# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-31 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timepost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_username', models.CharField(max_length=100)),
                ('tutor_pk', models.CharField(max_length=100)),
                ('course_name', models.CharField(default='', max_length=50)),
                ('course_number', models.IntegerField()),
                ('days', models.CharField(max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
    ]
