COURSE_CHOICES = (
    ('AANB', 'Applied Animal Biology'),
    ('ACAM', 'Asian Canadian and Asian Migration Studies'),
    ('ADHE', 'Adult and Higher Education'),
    ('AFST', 'African Studies'),
    ('AGEC', 'Agricultural Economics'),
    ('ANAT', 'Anatomy'),
    ('ANSC', 'Animal Science'),
    ('ANTH', 'Anthropology'),
    ('APBI', 'Applied Biology'),
    ('APPP', 'Applied Science Professional Program Platform'),
    ('APSC', 'Applied Science'),
    ('ARBC', 'Arabic Studies'),
    ('ARC', 'Alternative Routes to Computing'),
    ('ARCH', 'Architecture'),
    ('ARCL', 'Anthropological Archaeology'),
    ('ARST', 'Archival Studies'),
    ('ARTH', 'Art History'),
    ('ARTS', 'Arts One Program'),
    ('ASIA', 'Asian Studies'),
    ('ASIC', 'Arts and Science Interdisciplinary Courses'),
    ('ASLA', 'Asian Languages'),
    ('ASTR', 'Astronomy'),
    ('ASTU', 'Arts Studies'),
    ('ATSC', 'Atmospheric Science'),
    ('AUDI', 'Audiology and Speech Sciences'),
    ('BA', 'Business Administration: Core'),
    ('BAAC', 'Business Administration: Accounting'),
    ('BABS', 'Business Administration: Business Statistics'),
    ('BAEN', 'Business Administration: Entrepreneurship'),
    ('BAFI', 'Business Administration: Finance'),
    ('BAHC', 'Business Administration: Health Care'),
    ('BAHR', 'Business Administration: Human Resources Management'),
    ('BAIM', 'Business Administration: International Management'),
    ('BAIT', 'Business Administration: Business Technology Management'),
    ('BALA', 'Business Administration: Law'),
    ('BAMA', 'Business Administration: Marketing'),
    ('BAMS', 'Business Administration: Management Science'),
    ('BAPA', 'Business Administration: Policy Analysis'),
    ('BASC', 'Business Administration: Supply Chain'),
    ('BASD', 'Business Administration: Sustainable Development'),
    ('BASM', 'Business Administration: Strategic Management'),
    ('BATL', 'Business Administration: Transportation and Logistics'),
    ('BAUL', 'Business Administration: Urban Land Economics'),
    ('BIOC', 'Biochemistry'),
    ('BIOF', 'Bioinformatics'),
    ('BIOL', 'Biology'),
    ('BIOT', 'Biotechnology'),
    ('BMEG', 'Biomedical Engineering'),
    ('BOTA', 'Botany'),
    ('BRDG', 'Bridge Program'),
    ('BUSI', 'Business'),
    ('CAPS', 'Cellular, Anatomical and Physiological Sciences'),
    ('CCFI', 'Centre for Cross-Faculty Inquiry'),
    ('CCST', 'Critical and Curatorial Studies'),
    ('CDST', 'Canadian Studies'),
    ('CEEN', 'Clean Energy Engineering'),
    ('CELL', 'Cell and Developmental Biology'),
    ('CENS', 'Central, Eastern and Northern European Studies'),
    ('CHBE', 'Chemical and Biological Engineering'),
    ('CHEM', 'Chemistry'),
    ('CHIL', "Children's Literature"),
    ('CHIN', 'Chinese'),
    ('CICS', 'Computing Information and Cognitive Systems'),
    ('CIVL', 'Civil Engineering'),
    ('CLCH', 'Classical Chinese'),
    ('CLST', 'Classical Studies'),
    ('CNPS', 'Counselling Psychology'),
    ('CNRS', 'Classical, Near Eastern and Religious Studies'),
    ('CNTO', 'Cantonese'),
    ('COEC', 'Commerce Economics'),
    ('COGS', 'Cognitive Systems Program'),
    ('COHR', 'Commerce Human Resources'),
    ('COMM', 'Commerce'),
    ('COMR', 'Commerce Minor'),
    ('CONS', 'Natural Resources Conservation'),
    ('CPEN', 'Computer Engineering'),
    ('CPSC', 'Computer Science'),
    ('CRWR', 'Creative Writing'),
    ('CSIS', 'Critical Studies in Sexuality'),
    ('CSPW', 'Coordinated Science Program Workshop'),
    ('CTLN', 'Catalan'),
    ('DANI', 'Danish'),
    ('DENT', 'Dentistry'),
    ('DERM', 'Clinical Dermatology'),
    ('DES', 'Design'),
    ('DHYG', 'Dental Hygiene'),
    ('DMED', 'Digital Media'),
    ('DSCI', 'Data Science'),
    ('ECED', 'Early Childhood Education'),
    ('ECON', 'Economics'),
    ('ECPS', 'Educational & Counselling Psychology, & Special Education'),
    ('EDCP', 'Curriculum and Pedagogy'),
    ('EDST', 'Educational Studies'),
    ('EDUC', 'Education'),
    ('EECE', 'Electrical and Computer Engineering'),
    ('ELEC', 'Electrical Engineering'),
    ('ELI', 'English Language Institute'),
    ('EMBA', 'Executive M.B.A.'),
    ('ENDS', 'Environmental Design'),
    ('ENGL', 'English'),
    ('ENPH', 'Engineering Physics'),
    ('ENPP', 'Engineering and Public Policy'),
    ('ENVR', 'Environmental Science'),
    ('EOSC', 'Earth and Ocean Sciences'),
    ('EPSE', 'Educational Psychology and Special Education'),
    ('ETEC', 'Educational Technology'),
    ('EXCH', 'Exchange Programs'),
    ('EXGR', 'Exchange Graduate Research'),
    ('FACT', ' Commuter Transition Program'),
    ('FEBC', 'Forest Engineering British Columbia'),
    ('FHIS', 'French, Hispanic and Italian Studies'),
    ('FIPR', 'Film Production'),
    ('FISH', 'Fisheries Research'),
    ('FIST', 'Film Studies'),
    ('FMPR', 'Family Practice'),
    ('FMST', 'Family Studies'),
    ('FNEL', 'First Nations and Endangered Languages Program'),
    ('FNH', 'Food, Nutrition and Health'),
    ('FNIS', 'First Nations and Indigenous Studies'),
    ('FOOD', 'Food Science'),
    ('FOPR', 'Forest Operations'),
    ('FRE', 'Food and Resource Economics'),
    ('FREN', 'French'),
    ('FRSI', 'Forestry Silviculture Institute'),
    ('FRST', 'Forestry'),
    ('FSCT', 'Biochemistry and Forensic Science'),
    ('GBPR', 'Green Bioproducts'),
    ('GEM', 'Geomatics for Environmental Management'),
    ('GENE', 'Genetics'),
    ('GEOB', 'Geographical Sciences'),
    ('GEOG', 'Geography'),
    ('GERM', 'German'),
    ('GPP', 'Global Public Policy'),
    ('GREK', 'Greek'),
    ('GRS', 'Global Resource Systems'),
    ('GRSJ', 'Gender, Race, Sexuality and Social Justice'),
    ('GSAT', 'Genome Science and Technology'),
    ('HEBR', 'Hebrew'),
    ('HESO', 'Health and Society'),
    ('HGSE', 'Haida Gwaii Semesters'),
    ('HINU', 'Hindi-Urdu'),
    ('HIST', 'History'),
    ('HPB', 'High Performance Buildings'),
    ('HUNU', 'Human Nutrition'),
    ('IAR', 'Institute of Asian Research'),
    ('IEST', 'European Studies'),
    ('IGEN', 'Integrated Engineering'),
    ('INDE', 'Interdepartmental Medicine'),
    ('INDO', 'Indonesian'),
    ('INDS', 'Interdisciplinary Studies'),
    ('INFO', 'Information Studies'),
    ('ISCI', 'Integrated Sciences'),
    ('ITAL', 'Italian'),
    ('ITST', 'Italian Studies'),
    ('IWME', 'Integrated Water Management Engineering'),
    ('JAPN', 'Japanese'),
    ('JRNL', 'Journalism'),
    ('KIN', 'Kinesiology'),
    ('KORN', 'Korean'),
    ('LAIS', 'Library, Archival and Information Studies'),
    ('LARC', 'Landscape Architecture'),
    ('LASO', 'Law and Society'),
    ('LAST', 'Latin American Studies'),
    ('LATN', 'Latin'),
    ('LAW', 'Law'),
    ('LFS', 'Land & Food Systems'),
    ('LIBE', 'Teacher Librarianship'),
    ('LIBR', 'Library and Information Studies'),
    ('LING', 'Linguistics'),
    ('LLED', 'Language and Literacy Education'),
    ('LWS', 'Land and Water Systems'),
    ('MATH', 'Mathematics'),
    ('MDVL', 'Medieval Studies'),
    ('MECH', 'Mechanical Engineering'),
    ('MEDD', 'Doctor of Medicine'),
    ('MEDG', 'Medical Genetics'),
    ('MEDI', 'Medicine'),
    ('MGMT', 'Management	Vantage College'),
    ('MICB', 'Microbiology'),
    ('MIDW', 'Midwifery'),
    ('MINE', 'Mining Engineering'),
    ('MRNE', 'Marine Science'),
    ('MTRL', 'Materials Engineering'),
    ('MUSC', 'Music'),
    ('NAME', 'Naval Architecture and Marine Engineering'),
    ('NEST', 'Near Eastern Studies'),
    ('NEUR', 'Neurosurgery'),
    ('NRSC', 'Neuroscience'),
    ('NURS', 'Nursing'),
    ('OBMS', 'Oral Biological Medical Sciences'),
    ('OBST', 'Obstetrics and Gynaecology'),
    ('OHS', 'Oral Health Sciences'),
    ('ONCO', 'Oncology'),
    ('OPTH', 'Ophthalmology'),
    ('ORNT', 'Orientation to Medical School'),
    ('ORPA', 'Orthopaedics'),
    ('OSOT', 'Occupational Science and Occupational Therapy'),
    ('PAED', 'Paediatrics'),
    ('PATH', 'Pathology'),
    ('PCTH', 'Pharmacology and Therapeutics'),
    ('PERS', 'Persian'),
    ('PHAR', 'Pharmaceutical Sciences'),
    ('PHIL', 'Philosophy'),
    ('PHRM', 'Pharmacy'),
    ('PHTH', 'Physical Therapy'),
    ('PHYL', 'Cellular and Physiological Sciences'),
    ('PHYS', 'Physics'),
    ('PLAN', 'Community and Regional Planning'),
    ('PLAS', 'Plastic Surgery'),
    ('PLNT', 'Plant Science'),
    ('POLI', 'Political Science'),
    ('POLS', 'Polish'),
    ('PORT', 'Portuguese'),
    ('PSYC', 'Psychology'),
    ('PSYT', 'Psychiatry'),
    ('PUNJ', 'Punjabi'),
    ('RADI', 'Radiology'),
    ('RELG', 'Religious Studies'),
    ('RES', 'Resources, Environment and Sustainability'),
    ('RGLA', 'Religion, Literature and The Arts'),
    ('RHSC', 'Rehabilitation Sciences'),
    ('RMST', 'Romance Studies'),
    ('RSOT', 'Occupational Therapy'),
    ('RUSS', 'Russian'),
    ('SANS', 'Sanskrit'),
    ('SCAN', 'Scandinavian'),
    ('SCIE', 'Science'),
    ('SEAL', 'Southeast Asian Languages'),
    ('SGES', 'Smart Grid Energy Systems'),
    ('SLAV', 'Slavic Studies'),
    ('SOAL', 'South Asian Languages'),
    ('SOCI', 'Sociology'),
    ('SOIL', 'Soil Science'),
    ('SOWK', 'Social Work'),
    ('SPAN', 'Spanish'),
    ('SPHA', 'School of Population & Public Health'),
    ('SPPH', 'School of Population & Public Health'),
    ('STAT', 'Statistics'),
    ('STS', 'Science and Technology Studies'),
    ('SURG', 'Surgery'),
    ('SWED', 'Swedish'),
    ('THTR', 'Theatre'),
    ('TIBT', 'Tibetan Languages'),
    ('TRSC', 'Transition School'),
    ('UDES', 'Urban Design'),
    ('UFOR', 'Urban Forestry'),
    ('UKRN', 'Ukrainian'),
    ('UROL', 'Urological Surgery'),
    ('URST', 'Urban Studies'),
    ('URSY', 'Urban Systems'),
    ('VANT', 'Vantage College	Vantage College'),
    ('VGRD', 'Visiting Graduate Student'),
    ('VISA', 'Visual Arts'),
    ('VRHC', 'Vocational Rehabilitation Counselling'),
    ('VURS', 'Visiting Undergraduate Research Students'),
    ('WOOD', 'Wood Products Processing'),
    ('WRDS', 'Arts Studies in Writing'),
    ('WRIT', 'University Writing Centre Courses'),
    ('ZOOL', 'Zoology'),
)
