# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0003_auto_20170810_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userpk',
            field=models.CharField(default='error', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='comment',
            field=models.CharField(default='Not specified', max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='major',
            field=models.CharField(default='Not specified', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(default='Not specified', max_length=100),
        ),
    ]
