# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-28 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorapp', '0004_auto_20170828_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='major',
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.RemoveField(
            model_name='post',
            name='year',
        ),
    ]
